### PR TITLE
add dependecies for hsqldb db

### PR DESCRIPTION
**Pull request by aspacca**

### CODE REVIEW

**Comment by aspacca** [comment]
2.0.202 version released to maven, @FireMasterK can you try to run tests again?
thanks

**Comment by FireMasterK** [comment]
It fails, with a different error now!

**Comment by aspacca** [comment]
@FireMasterK 
without `MODE=PostgreSQL` and with `org.hibernate.dialect.H2Dialect` we get the following error:
```
ERROR: NULL not allowed for column "ID"; SQL statement:
insert into users (id, password, session_id, username) values (null, ?, ?, ?) [23502-202]
```

with `MODE=PostgreSQL` and `org.hibernate.dialect.PostgreSQL10Dialect` we get this one:
```
ERROR: Sequence "USERS_ID_SEQ" not found; SQL statement:
select currval('users_id_seq') [90036-202]
```

I would consider using hsqldb

**Comment by aspacca** [comment]
>The "MODE=" stuff is essentially unsupported at this point - none of the existing maintainers are interested,

**Comment by aspacca** [comment]
@FireMasterK 
h2 ibernate dialect is not working with version 2.0.202

I pushed a commit using hsqldb instead, please let me know what do you think.

**Comment by FireMasterK** [comment]
Merging this, although I haven't tested this since it looks good to me!

**Pull request merged**
