### PR TITLE
add dependecies for h2 db

### PR DESCRIPTION
**Pull request by aspacca**

### CODE REVIEW

**Comment by FireMasterK** [comment]
What also needs to be added is automated testing with h2, I'll push to this branch in a few hours.

**Comment by aspacca** [comment]
>What also needs to be added is automated testing with h2, I'll push to this branch in a few hours.

actually h2 has a problem on hibernate migration when restarting. I will investigate

**Comment by aspacca** [comment]
https://groups.google.com/g/h2-database/c/vq3Q7X3muJQ

**Comment by aspacca** [comment]
hsqldb has no problem

**Comment by FireMasterK** [comment]
Whoops, I accidentally pushed to the wrong branch, could you recreate this PR?

**Comment by FireMasterK** [comment]
I got the testing script to work in https://github.com/TeamPiped/Piped-Backend/commits/h2-database, I don't see the problem with h2?

**Comment by aspacca** [comment]
https://github.com/TeamPiped/Piped-Backend/pull/132

**Comment by aspacca** [comment]
>I don't see the problem with h2?

because you are using H2 Dialect, and no H2 with postgres mode
When you use postgres mode H2 documentantion instructs to use Postgres Dialect

my `config.properties`:
```
# Hibernate properties
hibernate.connection.url: jdbc:h2:/app/h2/piped;TRACE_LEVEL_FILE=3;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;TRACE_LEVEL_SYSTEM_OUT=3;;CASE_INSENSITIVE_IDENTIFIERS=TRUE
hibernate.connection.driver_class: org.h2.Driver
hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect

The problem is that the backend runs query without using hibernate ORM/Criteria API:
https://github.com/TeamPiped/Piped-Backend/blob/master/src/main/java/me/kavin/piped/Main.java#L36-L39
https://github.com/TeamPiped/Piped-Backend/blob/master/src/main/java/me/kavin/piped/Main.java#L75-L76

The two sql statements seems to be compatible with H2 in native mode but relying on that, especially if you'll introuce more hardcoded statements, could be error prone.
That's why I forced H2 in postgres mode (hsqldb has similar support).

Probably the best solution is to refactor those two statements to use hiberbnate ORM/Criteria API, what do you think?

**Comment by FireMasterK** [comment]
I thought the goal was to use h2 as a filedb :thinking:

**Comment by aspacca** [comment]
it used as filedb, just with postgres compatibility mode :)

**Pull request merged**
