### PR TITLE
don't allow duplicated videos in a playlist

### PR DESCRIPTION
**Pull request by Bnyro**
should resolve [TeamPiped/Piped#1002](https://github.com/TeamPiped/Piped/issues/1002)

### CODE REVIEW

**Comment by ChuckBartowski91** [comment]
Is this feature implemented? Because I can add a video more then once in a playlist.

**Comment by FireMasterK** [comment]
No, this is because we allow adding a video more than once to a playlist.

**Comment by ChuckBartowski91** [comment]
> No, this is because we allow adding a video more than once to a playlist.

So there is no way to disable it, am i correct?

**Comment by aneesh1122** [comment]
Dude what happened to this pull request?

**Pull request closed without merging**
