### PR TITLE
Use native SQL queries for removing from playlist.

### PR DESCRIPTION
**Pull request by FireMasterK**
Closes https://github.com/TeamPiped/Piped/issues/2783

### CODE REVIEW

**Comment by kuba1909** [comment]
This change introduces internal server errors for me when deleting some videos in a playlist:
```Aug 09, 2023 7:42:50 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
WARN: SQL Error: 0, SQLState: 23505
Aug 09, 2023 7:42:50 AM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
ERROR: ERROR: duplicate key value violates unique constraint "playlists_videos_ids_pkey"
  Detail: Key (playlist_id, videos_order)=(1, 27) already exists.
An error occoured in the path: /user/playlists/remove
org.hibernate.exception.ConstraintViolationException: JDBC exception executing SQL [UPDATE playlists_videos_ids SET videos_order = videos_order - 1 WHERE playlist_id = ? AND videos_order > ?] [ERROR: duplicate key value violates unique constraint "playlists_videos_ids_pkey"
  Detail: Key (playlist_id, videos_order)=(1, 27) already exists.] [n/a]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:95)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
	at org.hibernate.sql.exec.internal.StandardJdbcMutationExecutor.execute(StandardJdbcMutationExecutor.java:96)
	at org.hibernate.query.sql.internal.NativeNonSelectQueryPlanImpl.executeUpdate(NativeNonSelectQueryPlanImpl.java:76)
	at org.hibernate.query.sql.internal.NativeQueryImpl.doExecuteUpdate(NativeQueryImpl.java:834)
	at org.hibernate.query.spi.AbstractQuery.executeUpdate(AbstractQuery.java:637)
	at me.kavin.piped.server.handlers.auth.AuthPlaylistHandlers.removeFromPlaylistResponse(AuthPlaylistHandlers.java:350)
	at me.kavin.piped.server.ServerLauncher.lambda$mainServlet$50(ServerLauncher.java:484)
	at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
	at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:249)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by kuba1909** [comment]
@FireMasterK maybe a flush between both updates will fix it? Unfortunately, I don't have time right now to test it by myself. Also, I am wondering why no one else came up with that issue yet. Can you reproduce it? Currently, I have exactly 25 videos in my playlist (with duplicate videos_order=23 instead 27), running a postgres 13 DB. What confuses me the most is that some videos can still be removed. :thinking: 

The corresponding table looks like this:
```
piped=# SELECT * FROM playlists_videos_ids WHERE playlist_id = 1;
 playlist_id |  videos_id  | videos_order 
-------------+-------------+--------------
           1 | XXXXXXXXXXX |            0
           1 | XXXXXXXXXXX |           15
           1 | XXXXXXXXXXX |           24
           1 | XXXXXXXXXXX |           20
           1 | XXXXXXXXXXX |           19
           1 | XXXXXXXXXXX |           18
           1 | XXXXXXXXXXX |           17
           1 | XXXXXXXXXXX |           16
           1 | XXXXXXXXXXX |           22
           1 | XX-XXXXXXXX |           21
           1 | XXXXXXXXXXX |           10
           1 | XXXXXXXXXXX |            9
           1 | XXXXXXXXXXX |            8
           1 | XXXXXXXXXXX |            7
           1 | XXXXXXXXXXX |            6
           1 | XXXXXXXXXXX |            5
           1 | XXXXXXXXXXX |           23
           1 | XXXXXX__XXX |           14
           1 | XXXXXXXXXXX |           13
           1 | XXXXXXXXXXX |           12
           1 | XXXXXXXXXXX |           11
           1 | XXXXXXXXXXX |            4
           1 | XXXXXXXXXXX |            3
           1 | XXXXXXXXXXX |            2
           1 | XXXXXXXXXXX |            1
```

**Comment by FireMasterK** [comment]
You likely might be running the Postgres Alpine Docker image, we switched away from it due to corruption issues.

You might also want to use https://github.com/tianon/docker-postgres-upgrade to upgrade to postgres 15 :)

**Comment by kuba1909** [comment]
Indeed, I was using the 13-alpine image. I switched to the debian based image and noticed, that only 5 out of that 25 videos are visible within the playlist, although the playlist counter still stays 25 and the videos are still stored in the database. Thanks for your hints, but I think I will go for a new (15) database instead of doing an upgrade. I will open up an issue in case my issue persists :)

**Comment by leepfrog-ger** [comment]
I think I found the root cause of this issue. The update statement may be flawed and - depending how the query is processed internally can lead to the described behaviour.

Details: https://github.com/TeamPiped/Piped/issues/2814#issuecomment-1703845716

**Pull request merged**
